apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::551495400474:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-104I48AHO8CH6
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::551495400474:role/UdacityFlaskDeployCBKubectlRole
      username: build
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2022-11-10T13:41:25Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1729"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: ad5346bf-da37-44a9-90f8-10e8b951d96f
