apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::551495400474:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-KFAST2DXP9IK
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters 
      rolearn : arn:aws:iam::551495400474:role/UdacityFlaskDeployCBKubctlRole
      username: build `
kind: ConfigMap
metadata:
  creationTimestamp: "2022-11-09T18:46:52Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1667"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: c24a1f02-db92-4f79-8010-91aa4a117d03
